import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeWrapper from "./ThemeWrapper";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Vfind - Find Your Dream Job",
  description: "Generated by Simplifytech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`} style={{ fontFamily: "var(--font-poppins)" }}>
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
